name: Deploy websites

on:
  push:
    branches: ["master"]

  workflow_dispatch:


concurrency:
  group: "websites"
  cancel-in-progress: true

jobs:
  websites:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    environment:
      name: master
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: install deps
        run: |
          yarn install --immutable | grep -v 'YN0013'

      - name: build
        run: |
          yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Deploy websites
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          port: 22
          key: ${{ secrets.KEY }}
          source: ${{ github.workspace }}/packages/example/build
          target: "/home/ubuntu/login-interface"
          strip_components: 5
          rm: true
